services:
  firebase:
    image: goatlab/firebase-emulator:1.2-arm64
    container_name: emulator
    ports:
      - "9199:9199"
      - "4000:4000"
      - "5088:5088"
    command: ["firebase", "emulators:start", "--only", "storage,logging", "--project", "fir-demo-project", '--config', "./startfirebase.json"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "localhost:4400/emulators"]
      interval: 10s
      start_period: 10s
      retries: 3
      timeout: 5s
  allure-cloud:
    build:
      dockerfile: Dockerfile
      context: .
    develop:
      watch:
        - action: sync+restart
          path: ./worker/lib
          target: /app/lib
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    container_name: allure-deployer
    env_file: .env.slack
    environment:
      FIREBASE_STORAGE_EMULATOR_HOST: 127.0.0.1:9199 # Dev mode
      STORAGE_BUCKET: "fir-demo-project.appspot.com"
      PREFIX: 'project-999'
      WEBSITE_ID: 'fir-demo-project'
      WEBSITE_EXPIRES: 12h
      KEEP_HISTORY: true # Default is true when STORAGE_BUCKET is provided
      KEEP_RESULTS: true # Default is false
      WATCH_MODE: false
      TTL_SECS: 6
    volumes:
#      - ./worker:/app #Dev only. This overrides the /app dir
      - ${PWD}/gcp-key.json:/credentials/key.json:ro
      - /Users/sokari/IdeaProjects/appium/reports/ios/allure-results:/allure-results
    cpus: 1
    mem_limit: 2048m
    network_mode: service:firebase
    depends_on:
      firebase:
        condition: service_healthy
