name: Build Docker
on:
  workflow_dispatch:
  push:
    tags:
      ["v*.**"]
    
jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          npm install --workspace=@allure/shared
          npm install --workspace=@allure/docker
          npm run build --workspaces
          npm run test --workspaces
          npm install --workspace=@allure/shared --omit-dev
          npm install --workspace=@allure/docker --omit-dev

      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sokari/allure-deployer:latest
            sokari/allure-deployer:${{ github.sha }}

  deploy-docker-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          npm install --workspace=@allure/shared
          npm install --workspace=@allure/action
          npm run build --workspaces
          npm install --workspace=@allure/shared --omit-dev
          npm install --workspace=@allure/action --omit-dev

      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            sokari/allure-deployer-action:latest
            sokari/allure-deployer-action:${{ github.sha }}
