name: Build & deploy
on:
  workflow_dispatch:
  push:
    tags:
      ["v*.**"]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          cd ./worker
          npm install && npm run build
          npm install --omit=dev

      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            sokari/allure-deployer:latest
            sokari/allure-deployer:${{ github.sha }}